-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 18:44:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(60) NOT NULL,
  `dataNasc` DATETIME NOT NULL,
  `documento` VARCHAR(14) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `deviceToken` VARCHAR(255) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `dtUpated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_ermissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_ermissoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME GENERATED ALWAYS AS (),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_usuario_permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idPermissao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario_permissao_tb_usuarios_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_tb_usuario_permissao_tb_ermissoes1_idx` (`idPermissao` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_permissao_tb_usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_permissao_tb_ermissoes1`
    FOREIGN KEY (`idPermissao`)
    REFERENCES `delivery`.`tb_ermissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tbl_estabelecimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tbl_estabelecimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `phone` VARCHAR(11) NULL,
  `description` VARCHAR(150) NULL,
  `urlImage` VARCHAR(255) NULL,
  `latitude` VARCHAR(15) NOT NULL,
  `longigute` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `addressNumber` VARCHAR(6) NOT NULL,
  `addressOptional` VARCHAR(15) NULL,
  `status` VARCHAR(1) NULL,
  `dtCreated` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `dtUpdated` DATETIME NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_tbl_estabelecimentos_tb_usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_estabelecimentos_tb_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(110) NULL,
  `dtCreated` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `value` DOUBLE NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `dtUpdated` DATETIME NULL,
  `idCategoria` INT NOT NULL,
  `idEstabelecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categorias1_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tbl_estabelecimentos1_idx` (`idEstabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `delivery`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tbl_estabelecimentos1`
    FOREIGN KEY (`idEstabelecimento`)
    REFERENCES `delivery`.`tbl_estabelecimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `dtUpdated` DATETIME NULL,
  `idUsuario` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_vendas_tb_usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_tb_vendas_tb_produtos1_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_vendas_tb_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_vendas_tb_produtos1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `delivery`.`tb_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_push` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `dtCreated` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `dtUpdated` DATETIME NULL,
  `tb_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_push_tb_usuarios1_idx` (`tb_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_push_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
